version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo-user:27017/userdb
    depends_on:
      - mongo-user

  mongo-user:
    image: mongo
    container_name: mongo-user
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-user-data:/data/db

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo-product:27017/productdb
    depends_on:
      - mongo-product

  mongo-product:
    image: mongo
    container_name: mongo-product
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-product-data:/data/db

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo-order:27017/orderdb
    depends_on:
      - mongo-order

  mongo-order:
    image: mongo
    container_name: mongo-order
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo-order-data:/data/db
volumes:
  mongo-user-data:
  mongo-order-data:
  mongo-product-data:
