apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order-service
spec:
  replicas: 2 #initial pod count
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: soa-order-service
        image: ghcr.io/YOUR_GITHUB_USER/soa-order-service:latest
        ports:
          - containerPort: 3001
        env:
          - name: MONGO_URI
            value: "mongodb://mongodb:27017/orderdb"
        resources:
            requests:
              cpu: "100m"    # Minimum CPU
              memory: "128Mi"
            limits:
              cpu: "500m"    # Max CPU before scaling
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 3003
  type: ClusterIP
