name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_USER: ${{ secrets.GHCR_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push user-service image
        run: |
          docker build -t $REGISTRY/$IMAGE_USER/soa-user-service:latest ./user-service
          docker push $REGISTRY/$IMAGE_USER/soa-user-service:latest

      - name: Build and push product-service image
        run: |
          docker build -t $REGISTRY/$IMAGE_USER/soa-product-service:latest ./product-service
          docker push $REGISTRY/$IMAGE_USER/soa-product-service:latest

      - name: Build and push order-service image
        run: |
          docker build -t $REGISTRY/$IMAGE_USER/soa-order-service:latest ./order-service
          docker push $REGISTRY/$IMAGE_USER/soa-order-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/order-deployment
          kubectl rollout status deployment/product-deployment
          kubectl rollout status deployment/user-deployment
